// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require('Verifier');

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
contract('Verifier', accounts => {

    const account_one = accounts[0];
    const account_two = accounts[1];

    describe('testing Verifier', function () {
        beforeEach(async function () {
            this.contract = await Verifier.new({
                from: account_one
            });
        })

        it('with correct proof', async function () {
            let CorrectProof = {
                "A":["0xef4efcf17f3d5604c65910aa571d226b1a87008789a0576f7983e5b0ee8e060", "0xbed166763a8c2c998a960da10103680ffd494063c4fa796dacd82bdc9dd2ec8"],
                "B":
                    [["0xad80aa9f5e4378ef0dc942e3bd724668ec58074bf6565f7d7ca2e144c4a3f5a", "0x5601a954a648e4df2326828365c7531cdaa8da5824575a5d898342f676c4f60"], ["0x9517b7585accbfd3dac84f6dbf400f624418ec13bd974a0963b9ffb5e8f7fa6", "0x1628345512b0aaca29e1f03d27d0b43055e9de4d28aeeaf1f60c66eda1710196"]],
                
                "C":["0x6820de3f068c288ad843e0d920481ff87d37c09838e6b00d705fdc733d26575", "0x12e04c39436202e57a66af4bba3370f974577434b3e003af649e6b61a1a31278"],
                "input": [3, 1]
            }
            let result = await this.contract.verifyTx.call(CorrectProof.A, CorrectProof.B, CorrectProof.C, CorrectProof.input);
            assert.equal(result, false, "Proof is not correct");
        })

        // Test verification with incorrect proof
        it('with incorrect proof', async function () {
            let IncorrectProof = {
                "A": ["0x1f5949a6173ca35c35f29e4f5ba2f2bf8bc1d21e393bed068e5a98e2580a4c72", "0x227863acc81fd032be79580fb7e5b38e82b400b898bc02668261e46cf85f8da3"],
                "B": [
                    ["0x12d8e35611a54a640ae4b9f415afeef79b119c9defa1f120dd173f15c674eefc", "0x1852bfdaa3545201b1c11b6044182ab4ef9f3cb997bc8c2c9e121aa3214d09a1"],
                    ["0x6f5567c8d594dd49866d65c94f4e8f2b1ecf37ef3620e68afe4e66bfd9d1c48", "0x2f2244bc84bbc80b88a1aa053c7cd2e2a4ff3a1cb8c1f5471837a1a6c5e43d34"]
                ],
                "C": ["0xff134d886b7cd8b5d0580b13b7ee17757dd0c5d960bf692fc7faa433e30aad4", "0xcf1a56e9b39ef8eacebd14a848e0e876c5ae057ee8d8451e3b293b72f9b8c62"],
                "input": [3, 1]
            }
            let result = await this.contract.verifyTx.call(IncorrectProof.A, IncorrectProof.B, IncorrectProof.C, IncorrectProof.input);
            assert.equal(result, false, "Proof is not correct");
        })
    });
})