// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require('Verifier');

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
contract('Verifier', accounts => {

    const account_one = accounts[0];
    const account_two = accounts[1];

    describe('testing Verifier', function () {
        beforeEach(async function () {
            this.contract = await Verifier.new({
                from: account_one
            });
        })

        it('with correct proof', async function () {
            let CorrectProof = {
                "proof": {
                    "a": ["0x1ba0df5159c4c75da8a30d34e28b0a2242b9634aed77c9b41b979e6081ed5033", "0x04a81e18c8c57362b000213bce6d533055ba4f830dc76abf9c5bf37907ffbdd0"],
                    "b": [["0x272c1132c59a11b904df2e3921eaf7b40ce948a1a24e9b36dd6e2e04cc3e9560", "0x1535e1e6c5cb4d685ef68595487910d68d8813765f422b977b53e32f8c53fc94"], ["0x26e8a26d9bd754c038c42bb9b5b32b91a0c1463aba53b03eb8e224f1230f853a", "0x2c080f65faca972f26229da56b338fc12d62261f8626ec42659bc1090e7a983d"]],
                    "c": ["0x08c833d09a989255fa84bd16e9b4374fbf2c59f92f8b67298771b72c03e56f7f", "0x2f85944aef8c9f217463077e0d8f85fdf5546b3b570820ade0cf9c95a3feb440"]
                },
                "inputs": [9, 1]
            }
            let result = await this.contract.verifyTx.call(CorrectProof.a, CorrectProof.b, CorrectProof.c, CorrectProof.inputs);
            // line 27 leads to an error - but it is similar to line 43, which works
            assert.equal(result, true, "Proof is correct");
        })

        // Test verification with incorrect proof
        it('with incorrect proof', async function () {
            let IncorrectProof = {
                "A": ["0x1f5949a6173ca35c35f29e4f5ba2f2bf8bc1d21e393bed068e5a98e2580a4c72", "0x227863acc81fd032be79580fb7e5b38e82b400b898bc02668261e46cf85f8da3"],
                "B": [
                    ["0x12d8e35611a54a640ae4b9f415afeef79b119c9defa1f120dd173f15c674eefc", "0x1852bfdaa3545201b1c11b6044182ab4ef9f3cb997bc8c2c9e121aa3214d09a1"],
                    ["0x6f5567c8d594dd49866d65c94f4e8f2b1ecf37ef3620e68afe4e66bfd9d1c48", "0x2f2244bc84bbc80b88a1aa053c7cd2e2a4ff3a1cb8c1f5471837a1a6c5e43d34"]
                ],
                "C": ["0xff134d886b7cd8b5d0580b13b7ee17757dd0c5d960bf692fc7faa433e30aad4", "0xcf1a56e9b39ef8eacebd14a848e0e876c5ae057ee8d8451e3b293b72f9b8c62"],
                "input": [3, 1]
            }
            let result = await this.contract.verifyTx.call(IncorrectProof.A, IncorrectProof.B, IncorrectProof.C, IncorrectProof.input);
            assert.equal(result, false, "Proof is not correct");
        })
    });
})